# Generated by Django 4.2.28 on 2026-02-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user_id', 'post'), name='unique_like'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
